"""add rating, kast%, adr, hs% columns to the player_map_statistics table

Revision ID: 66a232da7ef5
Revises: 7ca6c654c473
Create Date: 2025-09-03 16:46:38.687696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a232da7ef5'
down_revision: Union[str, Sequence[str], None] = '7ca6c654c473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
