"""add rating, kast%, adr, hs% columns to the player_map_statistics table

Revision ID: 7143881c587e
Revises: 66a232da7ef5
Create Date: 2025-09-03 16:48:03.819135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7143881c587e'
down_revision: Union[str, Sequence[str], None] = '66a232da7ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_map_statistics', sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('player_map_statistics', sa.Column('kast_percent', sa.Integer(), nullable=False))
    op.add_column('player_map_statistics', sa.Column('adr', sa.Integer(), nullable=False))
    op.add_column('player_map_statistics', sa.Column('hs_percent', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_map_statistics', 'hs_percent')
    op.drop_column('player_map_statistics', 'adr')
    op.drop_column('player_map_statistics', 'kast_percent')
    op.drop_column('player_map_statistics', 'rating')
    # ### end Alembic commands ###
