"""all stats except kills, deaths, and assists can be nullable in the player_map_statistics table

Revision ID: 737f74ef54e3
Revises: f530ca209aeb
Create Date: 2025-09-24 11:02:31.335963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737f74ef54e3'
down_revision: Union[str, Sequence[str], None] = 'f530ca209aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_map_statistics', 'acs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_map_statistics', 'adr',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_map_statistics', 'hs_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_map_statistics', 'first_kills',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_map_statistics', 'first_deaths',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_map_statistics', 'first_deaths',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_map_statistics', 'first_kills',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_map_statistics', 'hs_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_map_statistics', 'adr',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_map_statistics', 'acs',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
