"""add assists column to the player_map_statistics table

Revision ID: 7ca6c654c473
Revises: 9de524f54e33
Create Date: 2025-09-03 16:31:27.255388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca6c654c473'
down_revision: Union[str, Sequence[str], None] = '9de524f54e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_map_statistics', sa.Column('assists', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_map_statistics', 'assists')
    # ### end Alembic commands ###
