"""remove region column from the Team table

Revision ID: 9de524f54e33
Revises: a9a6269def35
Create Date: 2025-08-28 12:37:54.153813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de524f54e33'
down_revision: Union[str, Sequence[str], None] = 'a9a6269def35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
