"""remove vlr, startdate, enddate columns form the Core table

Revision ID: a9a6269def35
Revises: b5ca16a832ef
Create Date: 2025-08-28 11:57:29.886648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a6269def35'
down_revision: Union[str, Sequence[str], None] = 'b5ca16a832ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cores_vlr_id_key'), 'cores', type_='unique')
    op.drop_column('cores', 'start_date')
    op.drop_column('cores', 'vlr_id')
    op.drop_column('cores', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cores', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('cores', sa.Column('vlr_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cores', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('cores_vlr_id_key'), 'cores', ['vlr_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
