"""rating and kast can be nullable in the player_map_statistics table

Revision ID: f530ca209aeb
Revises: 7143881c587e
Create Date: 2025-09-09 22:42:17.516921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f530ca209aeb'
down_revision: Union[str, Sequence[str], None] = '7143881c587e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_map_statistics', 'rating',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('player_map_statistics', 'kast_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('players_duels', sa.Column('map_played_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('players_duels_map_player_id_fkey'), 'players_duels', type_='foreignkey')
    op.create_foreign_key(None, 'players_duels', 'maps_played', ['map_played_id'], ['id'])
    op.drop_column('players_duels', 'map_player_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_duels', sa.Column('map_player_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'players_duels', type_='foreignkey')
    op.create_foreign_key(op.f('players_duels_map_player_id_fkey'), 'players_duels', 'maps_played', ['map_player_id'], ['id'])
    op.drop_column('players_duels', 'map_played_id')
    op.alter_column('player_map_statistics', 'kast_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_map_statistics', 'rating',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    # ### end Alembic commands ###
